package redesmedicasdesktop.Vista;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author antony
 */
public class VPanelDiaCalendario extends javax.swing.JPanel {

    /**
     * Creates new form JpnlDiaCalendario
     */
    public String dia = "";
    public JTextField txtDia;
    public JLabel lblTexto;

    public VPanelDiaCalendario() {
        initComponents();
        this.cargarComponentes();
    }

    public void cargarComponentes() {
        this.setBackground(Color.white);
        this.setLayout(new BorderLayout());
        this.txtDia = new JTextField();
        this.txtDia.setText(this.dia);
        this.txtDia.setSize(5, 5);
        this.add(BorderLayout.NORTH, txtDia);
        lblTexto = new JLabel();
        lblTexto.setText("<html>Cupos<br> 10 disponibles<br> 10 reservados</html>");
        this.add(BorderLayout.SOUTH, lblTexto);
        //this.repaint();
        this.setBorder(BorderFactory.createLineBorder(Color.black));

    }

    public String getDia() {
        return dia;
    }

    public void setDia(String dia) {
        this.dia = dia;
    }

    //GETTERS Y SETTERS
    public JTextField getTxtDia() {

        return txtDia;
    }

    public void setTxtDia(JTextField txtDia) {
        this.txtDia = txtDia;
        //this.repaint();
    }

    public void setTextoTxtDia(String txtDia) {
        this.txtDia.setText(txtDia);
        //this.repaint();
    }

    public String getTextoTxtDia() {
        return this.txtDia.getText();
        //this.repaint();
    }

    public JPanel getPanel() {
        return this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        System.out.println(this.getTextoTxtDia());
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
